name: .NET 6 API CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish -c Release -o '${{ github.workspace }}/out'
  
    - name: Zip Package
      run: |
        cd ${{ github.workspace }}/out 
        zip -r ${{ github.workspace }}/out.zip *
           
              
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: testapinet6
        environment_name: Testapinet6-env
        aws-region: us-east-1
        version_label: ${{ github.run_id}}
        version_description: ${{github.sha}}
        deployment_package: ${{github.workspace}}
